- backend/src/channel/channel.entity.ts
- backend/src/memo/memo.entity.ts
- backend/src/memos/memos.entity.ts
- backend/src/playlist/playlist.entity.ts
- backend/src/playlist/playlist_video.entity.ts
- backend/src/users/users.entity.ts
- backend/src/video/video.entity.ts
- 객체들의 연관관계를 바탕으로 엔티티 클래스 작성
<br />
- 유튜브 API를 가져올 때, 변수명이 다를 수 있어서 수정이 필요할 수 있음
> [BE] 엔티티 클래스 작성

- backend/src/memos/dto/create-memos.dto.ts
- backend/src/memos/memos.controller.ts
- backend/src/memos/memos.entity.ts
- backend/src/memos/memos.service.spec.ts
- backend/src/memos/memos.service.ts
- backend/src/video/video.entity.ts
> Memos 모듈 수정

- backend/src/app.module.ts
- backend/src/playlist/dto/create-playlist.dto.ts
- backend/src/playlist/dto/playlist-response.dto.ts
- backend/src/playlist/playlist.module.ts
- backend/src/playlist/playlist.service.spec.ts
- backend/src/playlist/playlist.service.ts
- backend/src/users/users.entity.ts
- backend/src/users/users.service.ts
- backend/src/vemo/vemo.controller.ts
- backend/src/vemo/vemo.service.spec.ts
- backend/src/vemo/vemo.service.ts
- backend/src/video/video.service.ts
> ✨ Feat: Vemo 페이지 재생목록 기능 구현

- backend/src/memos/memos.entity.ts
- backend/src/memos/memos.service.ts
- backend/src/vemo/vemo.controller.ts
- backend/src/vemo/vemo.service.spec.ts
- backend/src/vemo/vemo.service.ts
- #79 
커뮤니티 나의 글 보기 기능을 추가했습니다.
> feat: 커뮤니티 나의 글보기 기능 추가

- backend/src/home/dto/create-playlist-with-memos-response.dto.ts
- backend/src/home/home.controller.ts
- backend/src/home/home.service.ts
- #82 
- 
- home 페이지 요청 URL 변경
- create 함수 변경
> 🔨 Refactor: Home 페이지 리팩터링

- backend/src/playlist/playlist.service.ts
- backend/src/vemo/vemo.controller.ts
- backend/src/vemo/vemo.service.spec.ts
- backend/src/vemo/vemo.service.ts
> refactor: playlist 반환  메서드 수정

- backend/src/home/dto/create-memos-response.dto.ts
- backend/src/home/dto/create-playlist-with-memos-response.dto.ts
- backend/src/home/home.controller.ts
- backend/src/home/home.service.ts
- #87 
home 화면에서 카드를 클릭했을 때,
해당영상에 대한 나의 메모가 존재하지 않으면 생성,
해당 영상에 대한 나의 메모가 존재하면 가장 최신에 작성한 메모를 반환
> feat: home 화면 memos 생성 메서드 추가

- backend/src/users/dto/playlist-list.response.dto.ts
- backend/src/users/dto/updateUser.requests.dto.ts
- backend/src/users/users.controller.ts
- backend/src/users/users.service.ts
- #86 
playlist 받아오는 기능 구현, user Profile 수정 기능 구현
> feat: mypage 기능 구현

- backend/src/app.module.ts
- backend/src/text-extraction/dto/text-extraction.dto.ts
- backend/src/text-extraction/text-extraction.controller.ts
- backend/src/text-extraction/text-extraction.module.ts
- backend/src/text-extraction/text-extraction.service.ts
- #102 
부분 캡쳐 이미지에서 텍스트를 추출하는 기능 구현
> feat: 텍스트 추출 기능 구현

- backend/src/captures/captures.service.spec.ts
- #116 
- 
captures 서비스 테스트 작성
> test: captures 서비스 테스트 작성

- backend/src/playlist/playlist.service.spec.ts
> test: playlist 서비스 테스트 작성

- backend/src/home/home.controller.ts
- backend/src/home/home.service.ts
> refactor: page limit 설정 변경

- backend/src/pdf/pdf.controller.ts
- backend/src/pdf/pdf.service.ts
- frontend/src/app/vemo/[vemo]/components/exportButton/ExportButton.tsx
- #136 
- 내보내기 기능 및 api 구현 완료 -> 테스트 완료
> feat: 내보내기 기능 및 api 구현 완료, 테스트 완

- backend/src/text-extraction/dto/text-extraction.dto.ts
- backend/src/text-extraction/text-extraction.controller.ts
- backend/src/text-extraction/text-extraction.service.ts
- frontend/src/app/vemo/[vemo]/components/editor/MemoItem.tsx
- frontend/src/app/vemo/[vemo]/components/editor/editor.tsx
- frontend/src/app/vemo/[vemo]/components/extractButton/ExtractButton.tsx
- frontend/src/app/vemo/[vemo]/components/sideBarNav/sideBarNav.tsx
- #185 
- 이미지 저장 방식 변경으로 s3 url 관련 로직 추가
- 추출하기시 텍스트 인풋박스로 전달
- 인풋박스 전달 시 기존 부분캡처 이미지 삭제
> 추출하기 관련 기능 완료

- backend/src/captures/captures.module.ts
- backend/src/captures/captures.service.ts
- Captures memosID 안받아지는 문제 수정 
-  memo에서 발생했던 오류와 동일 #182
> feat: aptures memosID 안받아지는 문제 수정 

- backend/src/subtitles/subtitles.service.ts
> chore: env 변경 (환경에 따른 로컬 프록시 사용)

- backend/src/captures/captures.module.ts
- backend/src/vemo/vemo.controller.ts
- backend/src/vemo/vemo.module.ts
- backend/src/vemo/vemo.service.ts
> feat: 커뮤니티 퍼가기 기능 구현

- backend/src/captures/captures.module.ts
- backend/src/vemo/vemo.controller.ts
- backend/src/vemo/vemo.module.ts
- backend/src/vemo/vemo.service.ts
- frontend/src/app/vemo/[vemo]/components/community/Community.module.css
- frontend/src/app/vemo/[vemo]/components/community/Community.tsx
- frontend/src/app/vemo/[vemo]/page.tsx
- #195
- 전체보기, 내글보기 -> 퍼가기 버튼 기능 분리
- 전체보기 -> 글상세보기 추가 구현
- 전체보기 -> 퍼가기 기능 구현 (퍼가기 클릭 시 내 작성하기로)
- 내글보기 -> 수정하기(추가 작성하기) 구현
- 내글보기 -> 내글보기에서 내 메모 삭제 구현
> 전체글보기(글상세보기, 퍼가기) , 내글보기(작성하기)

- backend/src/main.ts
> fix: HTTP 요청 크기 제한 설정 추가

- backend/src/quiz/quiz.service.ts
- backend/src/summarization/summarization.service.ts
- DB 저장 최대 3번까지 시도 
- 프롬프트 response로 가끔 [MM:SS] ~[MM:SS] 의 형식으로 반환
- 떄문에 프롬프트 명령어 수정
> DB 저장 최대 3번 시도 & 프롬프트 수정

- backend/src/main.ts
> Frontend deploy

- frontend/src/app/vemo/[vemo]/components/editor/editor.tsx
- #223 
- 타임스탬프 생성 시점 변경 ( 엔터 -> 입력창 입력시작 시점)
> 에디터관련 수정(타임스탬프 시점)

- frontend/src/app/vemo/[vemo]/components/editor/editor.tsx
- #229 
- 메모 작성시 자동 스크롤
- 캡처 작성시 자동 스크롤
> 에디터: 메모 작성 및 캡처시 자동 스크롤 기능 추가

- frontend/src/app/vemo/[vemo]/components/editor/MemoItem.tsx
- frontend/src/app/vemo/[vemo]/components/editor/editor.tsx
- package-lock.json
- package.json
- #231 
- 에디터: 볼드, 이탈릭, 언더라인 추가
> 에디터: 볼드,이탈릭, 언더라인 추가

- backend/src/captures/captures.service.ts
- backend/src/vemo/vemo.service.ts
> fix: 커뮤니티 퍼가기 이미지 업로드 문제 해결

- frontend/src/app/vemo/[vemo]/components/sideBarNav/sideBarNav.tsx
- #233 
- 메모의 타이틀 제목이 표시되도록 하드코딩된 부분 수정
> 메모 제목 하드 코딩 수정

- backend/package.json
- frontend/src/app/vemo/[vemo]/components/sideBarNav/sideBarNav.module.css
- frontend/src/app/vemo/[vemo]/components/sideBarNav/sideBarNav.tsx
- package-lock.json
> 메모 제목 수정 기능 구현

- frontend/src/app/components/Layout/DropDownMenu.module.css
- frontend/src/app/components/Layout/Header.module.css
- frontend/src/app/components/Layout/SearchBox.module.css
> 헤더 컴포넌트 CSS 시연에 적합하게 수정

- frontend/src/app/components/Layout/Header.module.css
- frontend/src/app/components/Layout/SearchBox.tsx
- frontend/src/app/components/category/Category.module.css
- frontend/src/app/components/mainCard/MainCard.module.css
- frontend/src/app/components/mainCard/MainCard.tsx
- frontend/src/app/page.module.css
- #243 
- 1920*1080으로 시연에 적합하게 확대 수정
> 홈페이지 css수정(1920*1080)

- backend/src/pdf/pdf.controller.ts
- backend/src/pdf/pdf.module.ts
- backend/src/pdf/pdf.service.ts
- backend/src/pdf/pdf.utils.ts
- backend/src/quiz/quiz.service.ts
- backend/src/summarization/summarization.service.ts
> PDF 기능 및 CSS 수정

- backend/src/quiz/quiz.service.ts
- backend/src/summarization/summarization.service.ts
> bastion ip 주소 변경

- frontend/src/app/page.module.css
- frontend/src/app/vemo/[vemo]/components/editor/MemoItem.tsx
- frontend/src/app/vemo/[vemo]/components/editor/editor.tsx
- frontend/src/app/vemo/[vemo]/components/exportButton/ExportButton.tsx
- frontend/src/app/vemo/[vemo]/components/sideBarNav/sideBarNav.module.css
- frontend/tsconfig.json
- #251 
- 타임스탬프 기준 변경
- 캡처시 자동 스크롤
- 추출하기
- 내보내기시 로딩
> fix: 타임스탬프, 캡쳐시 자동 스크롤, 추출하기, 내보내기

- frontend/src/app/vemo/[vemo]/components/editor/editor.module.css
- frontend/src/app/vemo/[vemo]/components/quizView/quizView.module.css
- frontend/src/app/vemo/[vemo]/components/sideBarNav/sideBarNav.module.css
- frontend/src/app/vemo/[vemo]/components/sideBarNav/sideBarNav.tsx
- frontend/src/app/vemo/[vemo]/components/summaryView/summaryView.module.css
> 베모페이지 css 수정

- backend/Dockerfile
- backend/docker-compose.yml
- backend/src/captures/captures.service.ts
- backend/src/pdf/pdf.service.ts
- backend/src/pdf/pdf.utils.ts
- bucket name 수정# 🪐 작업 내용
- bucket name 수정
> chore: bucket name 수정

- backend/src/app.module.ts
- frontend/src/app/vemo/[vemo]/components/DrawingCanvas/DrawingCanvas.tsx
- frontend/src/app/vemo/[vemo]/components/editor/editor.tsx
- frontend/src/app/vemo/[vemo]/page.tsx
- fix:그리기 도구 => 저장 후 바로 반영되지 않는 문제
> fix: 그리기 도구

- backend/src/captures/captures.service.ts
> feat: 캡쳐 이미지 캐싱

- frontend/src/app/vemo/[vemo]/components/community/Community.module.css
> 커뮤니티 스크롤 추가

- frontend/src/app/vemo/[vemo]/components/DrawingCanvas/DrawingCanvas.module.css
- frontend/src/app/vemo/[vemo]/components/extractButton/ExtractButton.module.css
> 그리기기능시 모달 창 레이아웃 맞춤

- frontend/src/app/(event)/intro/intro.module.css
> 이벤트페이지 css수정

- README.md
> chore: intro image add
